apiVersion: v1
kind: Pod
metadata:
    name: contactsui-pod
    labels:
        project: k8-intro-ui
spec:
    containers:
        - name: contactswebui
          image: rjdudley/contactswebui:2.0
          ports:
            - containerPort: 80
            